version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.6.10
    steps:
      - checkout
      - run: pip install pytest
      - run: pip install pytest-cov
      - run: pip install requests
      - run:
          name: Run tests
          environment:
                  RQLITED_PATH: rqlited
                  PYTHONPATH: src
          command: python setup.py test
