version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.6.10
    steps:
      - checkout
      - run: pip install pytest pytest-cov requests
      - run: |
              curl -L https://github.com/rqlite/rqlite/releases/download/v6.6.5/rqlite-v6.6.5-linux-amd64.tar.gz -o rqlite-v6.6.5-linux-amd64.tar.gz
              tar xvfz rqlite-v6.6.5-linux-amd64.tar.gz
              cp rqlite-v6.6.5-linux-amd64/rqlited /home/circleci/project/rqlited
      - run:
          name: Run tests
          environment:
                  RQLITED_PATH: /home/circleci/project/rqlited
                  PYTHONPATH: src
          command: python setup.py test
